srcdir = '.'
blddir = './build' #'../node_contacts_remote.build' #set an out of source tree build directory so source directory does not get messy

def set_options(opt):
  opt.tool_options("compiler_cxx")

def configure(conf):
  conf.check_tool("compiler_cxx")
  conf.check_tool("node_addon")
  # it simply calls pkg-config here to retrieve the headers and the libraries
  conf.check_cfg(package='libgcal', args='--cflags --libs', uselib_store='LIBGCAL')

def build(bld):
  bld.install_files(blddir, ['remote_contacts.js'])
  obj = bld.new_task_gen("cxx", "shlib", "node_addon") 
  obj.cxxflags = ["-g", "-D_FILE_OFFSET_BITS=64", "-D_LARGEFILE_SOURCE", "-Wall"]
  obj.target = "remotecontacts"
  obj.source = "src/node_contacts_gmail.cpp src/gAddressBook.cpp"
  obj.uselib = ['LIBGCAL']
