#! /usr/bin/env python
# -*- coding: utf-8 -*-  

""" webinos-buildall is a utility that builds all module.gyp files found on the directory it runs from (and its children)."""

import os
import os.path
import sys
import subprocess

def build_projects(argv):
  """ Build all module.gyp files traversing the folders"""
  toolsDir = os.path.dirname(os.path.realpath(__file__))
  if sys.platform == 'win32':
    webinosgyp = os.path.join(toolsDir,'webinos-gyp.bat');
  else:
    webinosgyp = os.path.join(toolsDir,'webinos-gyp');
  if not os.path.isfile(webinosgyp):
    print 'Could not locate webinos-gyp in %s' % webinosgyp
    return False
  else:
    print "Located webinos-gyp in %s" % webinosgyp
    for root, dirs, files in os.walk(os.getcwd()): # Walk directory tree
      for f in files:
        if f.lower() == 'module.gyp':
          print "Found a module.gyp file in %s" % root
          os.chdir(root)
          subprocess.call(["%s" % webinosgyp,"make"])		  
  return True
  
if __name__ == '__main__':
  # If this is called directly from python, then generate_project reading the command line args
  build_projects(sys.argv[1:])