// 
// This module reads an X509 PEM certificate as generated by openssl
//
var x509Reader = exports;
var dcrypt = require('dcrypt');
var fs = require('fs');

//Main entry point: read an X509 output string.
x509Reader.readFile = function (pemFileName, doneFn) {
    "use strict";
    var certPem = fs.readFileSync(pemFileName, 'ascii');
    var cert = dcrypt.x509.parse(certPem);
    doneFn(cert);
};
